version: "3.8"

services:
  db:
    image: postgres:17
    container_name: elanel_prod_db
    restart: unless-stopped
    env_file:
      - .env.server
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elanel_prod_web
    restart: unless-stopped
    env_file:
      - .env.server
    depends_on:
      - db
    volumes:
      - static_data:/app/staticfiles # STATIC_ROOT => /app/staticfiles
      - media_data:/app/elanelsystem/media # MEDIA_ROOT  => /app/elanelsystem/media
    expose:
      - "8000"

  caddy:
    image: caddy:2-alpine
    container_name: elanel_prod_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDY_EMAIL: ${CADDY_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - static_data:/var/www/staticfiles:ro
      - media_data:/var/www/media:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  pg_data:
  static_data:
  media_data:
  caddy_data:
  caddy_config:
